### ISSUE TITLE
Integrate new confounds infrastructure

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1540]
This issue corresponds to PR #1487.

Dependencies:

- [x] Get nipy/nipype#2878 finally merged, via #1539, and after tests on #1487 pass.
- [x] Pin niworkflows to the new DerivativesDatasink (poldracklab/niworkflows#308) and write integration code to write sidecars (relates to -if not fixes- #1301).
- [x] Address poldracklab/niworkflows#320
- [x] Finish up ~~#1487~~ now #1586

**Comment by oesteban** [comment]
@rciric you can pin
```
git+https://github.com/oesteban/niworkflows@72822f2a8dc5e77c3b989b912ba19aa34524dd7f#egg=niworkflows
```
to check the new ``meta_dict`` input of ``DerivativesDataSink``s.

**Comment by effigies** [comment]
I think this is done?

**Comment by oesteban** [comment]
Opened a follow-up here: #1616
