### ISSUE TITLE
Support custom templates

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1640]
This involves:
- [ ] Mounting the `--output-spaces` option in fmriprep-docker (similarly to #1462)
- [ ] Update templateflow client to index custom directories (templateflow/python-client#12)
- [ ] Update smriprep's argparse action (poldracklab/smriprep#87)
- [ ] Probably some adaptations in fmriprep proper
